spring:  mvc:    view:      prefix: /WEB-INF/views/      suffix: .jsp  datasource:    driver-class-name: com.mysql.cj.jdbc.Driver    url: jdbc:mysql://localhost:3306/dbcapston?allowMultiQueries=true&useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC    username: root    password: takiyoon1003  aop:    proxy-target-class: true  servlet:    multipart:      enabled: true      max-file-size: 20MB      max-request-size: 20MBmybatis:  type-aliases-package: com.reportcom:  report:    upload:      local-path: e:/upload      url-path: /upload              
#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/dbcapston?allowMultiQueries=true&useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=takiyoon1003
#mybatis.type-aliases-package=com.report
#spring.aop.proxy-target-class=true
#spring.servlet.multipart.enabled=true
#spring.servlet.multipart.max-file-size=20MB
#spring.servlet.multipart.max-request-size=20MB 
#com.report.upload.localPath=e:/upload
#com.report.upload.urlPath=/upload

#spring.servlet.multipart.max-file-size=20MB
#spring.servlet.multipart.max-request-size=20MB
#  업로드 파일 최대 크기 설정
#
#net.skhu.upload.localPath=e:/upload
#  파일을 저장할 파일시스템 경로명 설정.
#  File2Controller에서만 사용됨.
#  이 폴더를 반드시 미리 생성하여야 한다. 이 폴더가 없으면 실행할 때 에러.
#
#net.skhu.upload.urlPath=/upload
#  파일을 저장할 webapp 폴더 아래의 경로명 설정.
#  File3Controller에서만 사용됨.
#  이 폴더를 webapp 폴더 아래에 반드시 미리 생성하여야 한다. 이 폴더가 없으면 실행할 때 에러
